#Positions of the floating texts
Positions:
    - world: skyblock1
      x: -35
      y: 65
      z: 17
#API-Key of your server provided by minecraftpocket-servers.com
API-Key: "5mOEmFsRxLOvXOGtkYUUXjGfLwNPjiaT3x6"
#Amount of voters who shall be shown (Max: 500)
Amount: 10
#Update interval of the query to the server in seconds
Update-Interval: 180
#Header of the floating text particle
Header: "§l§e•§a TOP Vote Tháng Này §e•"
#Text for every row after the header
Text: "§l§3▶§c {player}: §e{votes} §3◀"
#Check if the name of a voter is valid
#Votes of invalidly named players will be discarded if enabled
Check-Name: true
#When set to true PocketVote will provide aggregated top voters instead of using your API-Key
Use-PocketVote: false