---
message:
- '§l§e•§a Key Lucky của bạn: §e{KEY}'
items:
- name: §l§6【§e Kiếm Lucky§6 】
  id: 276
  meta: 0
  amount: 1
  enchantments:
    protection:
      level: 110
    sharpness:
      level: 80
    fire_aspect:
      level: 30
    unbreaking:
      level: 40
  lore: |-
    §l§f⚫§b Độ Bền: §e✰ ✰ ✰ ✰§f ✰
    §l§f⚫§b Độ Hiếm: §e✰ ✰ ✰§f ✰ ✰
    §l§f⚫§b Sát Thương: §e✰ ✰ ✰ §f✰ ✰
    §l§f⚫§e Lưu Ý:§b Vật phẩm bị mất admin không chịu trách nhiệm
- name: §l§6【§e Cúp Lucky§6 】
  id: 278
  meta: 0
  amount: 1
  enchantments:
    fortune:
      level: 20
    efficiency:
      level: 50
    unbreaking:
      level: 60
  lore: |-
    §l§f⚫§b Độ Bền: §e✰ ✰ ✰§f ✰ ✰
    §l§f⚫§b Độ Hiếm: §e✰ ✰ ✰ §f✰ ✰
    §l§f⚫§b Tốc Độ: §e✰ ✰ ✰ ✰ §f✰
    §l§f⚫§e Lưu Ý:§b Vật phẩm bị mất admin không chịu trách nhiệm
- name: §l§6【§e Rìu Lucky§6 】
  id: 279
  meta: 0
  amount: 1
  enchantments:
    efficiency:
      level: 40
    unbreaking:
      level: 50
  lore: |-
    §l§f⚫§b Độ Bền: §e✰ ✰ §f✰ ✰ ✰
    §l§f⚫§b Độ Hiếm: §e✰ ✰ §f✰ ✰ ✰
    §l§f⚫§b Tốc Độ: §e✰ ✰ ✰ §f✰ ✰
    §l§f⚫§e Lưu Ý:§b Vật phẩm bị mất admin không chịu trách nhiệm
- name: §l§6【§e Lucky Block§6 】
  id: 19
  meta: 0
  amount: 16
  lore: §l§f⚫§e Lưu Ý:§b Vật phẩm bị mất admin không chịu trách nhiệm
- name: §l§6【§e Lucky Block§6 】
  id: 19
  meta: 0
  amount: 32
  lore: §l§f⚫§e Lưu Ý:§b Vật phẩm bị mất admin không chịu trách nhiệm
- name: §l§6【§e Lucky Block§6 】
  id: 19
  meta: 0
  amount: 8
  lore: §l§f⚫§e Lưu Ý:§b Vật phẩm bị mất admin không chịu trách nhiệm
- id: 57
  meta: 0
  amount: 64
- id: 42
  meta: 0
  amount: 64
- id: 152
  meta: 0
  amount: 64
- id: 41
  meta: 0
  amount: 64
- id: 173
  meta: 0
  amount: 64
- id: 22
  meta: 0
  amount: 64
- id: 133
  meta: 0
  amount: 64
...
